version: '3'
services:
  app:
    build: docker/php
    container_name: sportshop_app
    volumes:
      - ./:/var/www
    depends_on:
      - db
  nginx:
    image: nginx:1.21
    container_name: sportshop_nginx
    ports:
      - 1810:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/sportshop.local.conf:/etc/nginx/conf.d/sportshop.local.conf
      - ./docker/nginx/sportshoplaravel.local.conf:/etc/nginx/conf.d/sportshoplaravel.local.conf
    depends_on:
      - app
  db:
    platform: linux/x86_64
    image: mysql:8.0.23
    ports:
      - 33063:3306
    restart: always
    volumes:
      - ./docker/mysql/files:/var/lib/mysql
    container_name: sportshop_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: sportshop_db
      MYSQL_USER: sportshop_user
      MYSQL_PASSWORD: sportshop_pwd
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

